// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web.Data;

#nullable disable

namespace Web.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250816100623_MenuTable")]
    partial class MenuTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("Web.Models.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Link")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Link = "/Home/Index",
                            Title = "Home",
                            Type = "Main"
                        },
                        new
                        {
                            Id = 2,
                            Link = "/Shop/Index",
                            Title = "Shop",
                            Type = "Main"
                        },
                        new
                        {
                            Id = 3,
                            Link = "/Product/Details",
                            Title = "Product",
                            Type = "Main"
                        },
                        new
                        {
                            Id = 4,
                            Link = "/Blog/Index",
                            Title = "Blog",
                            Type = "Main"
                        },
                        new
                        {
                            Id = 5,
                            Link = "/Blog/Index",
                            Title = "Blog Pages",
                            Type = "Sub"
                        },
                        new
                        {
                            Id = 6,
                            Link = "/Blog/Details",
                            Title = "Blog Details",
                            Type = "Sub"
                        },
                        new
                        {
                            Id = 7,
                            Link = "/Cart/Index",
                            Title = "Cart",
                            Type = "Main"
                        },
                        new
                        {
                            Id = 8,
                            Link = "/Checkout/Index",
                            Title = "Checkout",
                            Type = "Main"
                        },
                        new
                        {
                            Id = 9,
                            Link = "#",
                            Title = "My Account",
                            Type = "Account"
                        },
                        new
                        {
                            Id = 10,
                            Link = "#",
                            Title = "Login",
                            Type = "Account"
                        },
                        new
                        {
                            Id = 11,
                            Link = "#",
                            Title = "Contact",
                            Type = "Account"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
