// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web.Data;

#nullable disable

namespace Web.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("Web.Models.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Link")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Link = "/Home/Index",
                            Title = "Home",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Link = "/Shop/Index",
                            Title = "Shop",
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Link = "/Product/Details",
                            Title = "Product",
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            Link = "/Blog/Index",
                            Title = "Blog",
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            Link = "/Cart/Index",
                            Title = "Cart",
                            Type = 0
                        },
                        new
                        {
                            Id = 8,
                            Link = "/Checkout/Index",
                            Title = "Checkout",
                            Type = 0
                        },
                        new
                        {
                            Id = 12,
                            Link = "/Wishlist/Index",
                            Title = "Wishlist",
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            Link = "/Blog/Index",
                            Title = "Blog Pages",
                            Type = 2
                        },
                        new
                        {
                            Id = 6,
                            Link = "/Blog/Details",
                            Title = "Blog Details",
                            Type = 2
                        },
                        new
                        {
                            Id = 9,
                            Link = "/Account/Index",
                            Title = "My Account",
                            Type = 3
                        },
                        new
                        {
                            Id = 10,
                            Link = "/Account/Login",
                            Title = "Login",
                            Type = 3
                        },
                        new
                        {
                            Id = 11,
                            Link = "/Contact/Index",
                            Title = "Contact",
                            Type = 3
                        },
                        new
                        {
                            Id = 14,
                            Link = "/Home/Index",
                            Title = "Home",
                            Type = 1
                        },
                        new
                        {
                            Id = 15,
                            Link = "/Shop/Index",
                            Title = "Shop",
                            Type = 1
                        },
                        new
                        {
                            Id = 16,
                            Link = "/Product/Details",
                            Title = "Product",
                            Type = 1
                        },
                        new
                        {
                            Id = 17,
                            Link = "/Blog/Index",
                            Title = "Blog",
                            Type = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
